### ISSUE TITLE
Tiling/Offset is not being made constant in shader optimizer

### ISSUE THREAD

**Issue by morerokk** [DarthShader/Kaj-Unity-Shaders#1]
Not sure why, but the Tiling/Offset of textures doesn't seem to be optimized away/turned into a constant. I tested it out on a simple Unlit shader. It correctly turns colors and floats into constants, but a texture's associated Tiling/Offset property can still be changed even after the lock-in.

I checked the shader optimizer code and didn't see anything strange. I stepped through it with the debugger and it does indeed add the corresponding `_ST` property to the `constantProps` list, but it's still not actually constant after that.

The generated shader file does not contain any `_ST` or `_TexelSize` constants whatsoever.

The issue happens both with and without a texture in the corresponding slot.

**Comment by DarthShader** [comment]
This is most likely because the default generated Unlit shader uses the `TRANSFORM_TEX` macro from `UnityCG.cginc`, which doesn't specifically use `_SomeTexture_ST` as an argument.  Thus its never used directly as a variable and not optimized.  Two alternatives are: 1. to manually multiply `_ST` variables and 2. use a copy of the `TRANSFORM_TEX` macro with a `//KSOEvaluateMacro` line above it.

I'm sorry there isn't much documentation for this shader or toolset - I completely lost interest in this project/Unity development as a whole after VRChat's continuous decline over the years.

**Comment by morerokk** [comment]
I see, that's a shame. Thanks for the detailed response!
